### ISSUE TITLE
Unable to stop tomcat using tomcatStop task

### ISSUE THREAD

**Issue by marcingrabda** [bmuschko/gradle-tomcat-plugin#112] opened 2014-10-30 05:12 UTC
This is what I have configured:

- in a test task:

```
doFirst {
    tasks.tomcatRunWar.daemon = true
    tasks.tomcatRunWar.execute()
}
doLast {               
    tasks.tomcatStop.execute()
}
```

also:

```
[tomcatRunWar, tomcatStop]*.stopPort = 8081
[tomcatRunWar, tomcatStop]*.stopKey = 'stopKey'
```

and this is what I am getting:

```
The web application [/avprm-ui] appears to have started a thread named [cluster-1-thread-1] but has failed to stop it. This is very likely to create a memory leak.

Failed to check for ThreadLocal references for web application [/avprm-ui]
java.lang.NullPointerException
        at org.apache.catalina.loader.WebappClassLoader.loadedByThisOrChild(WebappClassLoader.java:2607)
        at org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks(WebappClassLoader.java:2523)
        at org.apache.catalina.loader.WebappClassLoader.checkThreadLocalsForLeaks(WebappClassLoader.java:2478)
...
```

Is there anything I am missing?

**Comment by marcingrabda** [comment] 2015-01-09 03:16
@bmuschko It is tricky. The original project has a lot of dependencies and a very complex build.gradle file.

**Comment by olliefreeman** [comment] 2015-02-04 14:27
we are having the same issue, running using the tomcatRunWar daemon = true and then calling tomcatStop does not work. The ports are being left in TIME_WAIT status and we therefore have to call `gradle --stop` to free the ports before rerunning the tests

**Comment by bmuschko** [comment] 2015-02-04 14:30
Based on your comment `gradle --stop`, it sounds like this is only happening if you are using the Gradle daemon. Keep in mind that the plugin daemon != Gradle daemon.

**Comment by olliefreeman** [comment] 2015-02-04 14:31
```
apply plugin: 'war'
apply plugin: 'com.bmuschko.tomcat'
apply plugin: 'com.github.samueltbrown.cucumber'


ext {
   tomcatStopPort = 8081
   tomcatStopKey = 'stopKey'
}

boolean isFunctionalTestToRunInEmbeddedContainer() {
   System.getProperty('com.ijento.zeus.test.url') == null
}

task functionalTomcatRunWar(type: com.bmuschko.gradle.tomcat.tasks.TomcatRunWar) {
   httpPort = 8092
   stopPort = tomcatStopPort
   stopKey = tomcatStopKey
   daemon = true
   onlyIf {
      isFunctionalTestToRunInEmbeddedContainer()
   }
}

task functionalTomcatStop(type: com.bmuschko.gradle.tomcat.tasks.TomcatStop) {
   stopPort = tomcatStopPort
   stopKey = tomcatStopKey
   onlyIf {
      isFunctionalTestToRunInEmbeddedContainer()
   }
}

cucumber {
    formats = ['pretty',
               "html:$projectReportDirName/cucumber/${project.name}".toString(),
               "json:$projectReportDirName/cucumber/${project.name}.json".toString(),
    ]
    jvmOptions {
        systemProperties << [
            'com.ijento.token.url' : System.getProperty('com.ijento.token.url'),
            'com.ijento.sso.username' : System.getProperty('com.ijento.sso.username'),
            'com.ijento.sso.password' : System.getProperty('com.ijento.sso.password'),
            'com.ijento.zeus.test.url' : System.getProperty('com.ijento.zeus.test.url')
        ]
    }
}

// incantations to work around https://github.com/samueltbrown/gradle-cucumber-plugin/issues/38
tasks.cucumber.dependsOn tasks.functionalTomcatRunWar
tasks.cucumber.finalizedBy tasks.functionalTomcatStop
```

and we then also have the gradle daemon set to be true

**Comment by marcingrabda** [comment] 2015-02-23 04:11
I solved the problem by turning off gradle daemon...

**Comment by bmuschko** [comment] 2015-05-03 15:21
Can you try this with the latest version of the plugin? This just works fine for me with the Gradle daemon enabled:

    tomcat {
        contextPath = 'sample-app'
        daemon = true
    }

    task functionalTest {
        dependsOn tomcatRun
        finalizedBy tomcatStop
    
        doLast {
            println 'http://localhost:8080/sample-app'.toURL().text
        }
    }

I noticed that it takes a couple of seconds for the HTTP port to free up but it does eventually. I checked this with `lsof -i:8080`.

**Comment by bmuschko** [comment] 2015-05-09 15:30
I am going to close this issue as I can't reproduce the issue and there was no further response.

**Closed** 2015-05-09 15:31 UTC
Labels: Won't fix
