### ISSUE TITLE
Hot swap in multimodule project

### ISSUE THREAD

**Issue by barsifedron** [bmuschko/gradle-tomcat-plugin#101] opened 2014-07-10 12:33 UTC
Hi, I have a multi module project 

-build.gradle
-common
-extranet
-intranet

I have sources in 'common' and web pages in 'extranet'.
Running tomcatRun in extranet, i'd like to have hot swap if I make changes in 'common' sources.

I tried 

dependencies {
    compile (project(path: ':common')){ transitive = false } 
}

in the extranet project build file. The tomcatRun tasks runs properly. If i run gradle compileJava (in the 'extranet' folder ) though, even if common is compiled again, there is not reload of the classes in the running tomcat.

I was wondering if this is something that is supposed to work or if some specifics of my project might cause trouble.

**Comment by bmuschko** [comment] 2018-04-14 17:43
Closing as duplicate of https://github.com/bmuschko/gradle-tomcat-plugin/issues/81.

**Closed by bmuschko** 2018-04-14 17:43 UTC
